baseurl = "http://www.marcore.it/"
languageCode = "en-us"
title = "Marco Re"
copyright = "Â© 2015 Marco Re"
theme= "greyshade"
[author]
  name = "Marco Re"


[params]
  github_user="marcore"
  twitter_user="marcore78"
  linkedin_user="marcore1"
  google_analytics_tracking_id="UA-65943188-1"
